services:
  # Backend Service
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"   # Expose backend to port 8080
    environment:
      - MONGO_URI=mongodb+srv://sepp:recipes@recipes.jgfsn.mongodb.net  # MongoDB Atlas URI
    networks:
      - app-network

  # Frontend Service
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"   # Expose frontend to port 3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
